config:
  digitalocean:token:
    secure: AAABAOe6DMeYb5zcL1jm8BEkNM77e2g3p/yVTRDz0PjFSH7loz9xCP9zj/LIZto9dSz6Z8D5L/b6crkuMIWJICbz+s8tUtWnEtVtSuOslvPTcBRQGiedab5+NXx5KSRm+NkYCKuKIQ==
  cloudflare:apiToken:
    secure: AAABAMRwx9LI9BXh0gyzytJA0pSqu/1K52idH7/7ViLJW4mBuAbgVfDEc26+TbtmeNpsT8eSNF/5Bhh0otQnRi4xSFLRBUhKZzn00AUXh6TrA9HIhw==
  canyougrab-infra:ssh_key_fingerprint: "55156888"
  canyougrab-infra:release_version: v0.2.2
  canyougrab-infra:gh_token:
    secure: AAABAA6+gxXw2VSC5+1C4yH8aochQOZgkD76wdyIFNY3QtXzKWaOK0QLIOJvBORmWyNhb2WDOBSug9qMgfL/P/WwRXNCcW2J
