config:
  digitalocean:token:
    secure: AAABAGUa7QSi3zLT6OADmWMTxCkyNWz7hbgqdwomuMU2Z5ZqvZ4vUqRTZrm/BWOyv2JxD4m3ovTLBbTPm8FmccjPxpCwqcmbRp9l1rj1Ww8+zA6X4BIvOIm8k7QuKDLGlKEBHZjedQ==
  canyougrab-infra:ssh_key_fingerprint: "54934856"
  canyougrab-infra:region: nyc3
  canyougrab-infra:droplet_size: s-1vcpu-1gb
  canyougrab-infra:git_ref: main
  canyougrab-infra:repo_url: git@github.com:ericismaking/canyougrab-whois-engine.git
  canyougrab-infra:gh_token:
    secure: AAABAKvVqTd8I6jUIkaOM0iSopqRE+gVRcC6UzosQrwatIepw+/Qf7RiWE52zQJ4eYjqO719H6UvkzpP7U58YFjbMyKOua9c
  canyougrab-infra:release_version: v0.2.2
  cloudflare:apiToken:
    secure: AAABAAS4QHxTkuHXe0f+OD3TvH3T86Yfwa79KNbBtxFyfA8m+kG1wFeNQNyG/5Y8KpJc13XJWds39NShkTfAFuuyjVyo+TdUoou/90mrFm1eX9Lbhg==
