config:
  digitalocean:token:
    secure: AAABAN/dD++mmlUxA1yusJO1ltH77Twru/9SpKyJ0Lc7Qxoj6TaBELAnZr9mqm5FBrpQPio55HpnqX8JwuZuqi9J8yA7TnrYf1iC46pQPKsyhme7UYUMZ7L1aytYxDmhVeXhlskaow==
  canyougrab-infra:ssh_key_fingerprint: "55156888"
  canyougrab-infra:region: nyc3
  canyougrab-infra:droplet_size: s-1vcpu-1gb
  canyougrab-infra:git_ref: dev
  canyougrab-infra:postgres_password:
    secure: AAABANPgWwOdGXb8aOf0B3fjv3Fjm+2a9eO811cCAagXd6Qu/cpR3g15+ukSyU7SAy3WeFIGC1U=
  canyougrab-infra:valkey_password:
    secure: AAABACWGRJV0yoLlCq68Wl1zkTu9ca+Vii7fY2HJvQ9iVbmHLLkVT7YgVEKt/u8L6ONhMmDQh0M=
  canyougrab-infra:stripe_secret_key:
    secure: AAABAK/C4bbRUd/mfxVMytG6KdgnXHgzk4PHg8GkBhtq4eyHvvTn6GwrhxrGVhob+Xh1Mlt1f9OYvNVMBnw3BH+n3Mebom1IvzAaaqfBdssyK4evQ0qjnrhnNk2gc0AY2aJu0Zo9rohHulScsM7rWWs62DhJkEfe/VMhTImjQwks/77OAGSmjmvPRw==
  canyougrab-infra:stripe_webhook_secret:
    secure: AAABAGSC5c4b8MeWlpClSMACYWwVj5pGjMdFqFWR0ujDl7hzdRo1rtjwKc6Qu4bd5qZvhWJFksMiXlyeUQ1jKLY4NSwLDQ==
  cloudflare:apiToken:
    secure: AAABAKk9IFM2+pAXBX88EJv6kqiBQXLqnIyZ89Rv1/OK8K8lXF4jqKKyt7HiebpEsBMPcJys8/kUdPxwuSQYUo/8inW/SMj3mn34vosSevcTULfZCA==
  canyougrab-infra:postgres_host: db-postgresql-canyougrab-do-user-34997254-0.k.db.ondigitalocean.com
  canyougrab-infra:valkey_host: db-valkey-canyougrab-do-user-34997254-0.k.db.ondigitalocean.com
