config:
  digitalocean:token:
    secure: AAABAGNC18KWoMqwSW24P/YwRYP8QQ2oiFK2Kr4heRNnK9mM6TQxpJJ+m3cQUtap+6p80pzEHVKZiLgFqb0YSgJoHoFBqpY0JEy3ZI3DWiRhMe1S1w/VsaG3fMLLuIniJS1+Z8GgdA==
  cloudflare:apiToken:
    secure: AAABANSSvnkhNPi+LL7PUOIG0tc2WjVmtt7YP3xDhkGcrVl3HDvTH5a0zuexjzEPEnkjQXymrRAGwAFpNwuGQw9xXhZGm0BT+Qk53LpvWuHIeOnRsw==
  canyougrab-infra:ssh_key_fingerprint: "54934856"
  canyougrab-infra:region: nyc3
  canyougrab-infra:droplet_size: s-1vcpu-2gb
